theme: jekyll-theme-slate
show_downloads: true
navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: /index.md
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
